name: Build
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    if: (github.event_name == 'pull_request' && github.event.action == 'labeled') || github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 8
          cache: "gradle"
      - name: Build MineVNLib & get plugin informations
        run: |
          chmod +x ./gradlew
          ./gradlew assemble
          mkdir -p target
          cp ./minevnlib-plugin/build/libs/MineVNLib.jar ./target/MineVNLib.jar
          cp ./minevnlib-plugin/build/libs/MineVNLib-no-kotlin.jar ./target/MineVNLib-no-kotlin.jar
          echo "hash=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "version=$(./gradlew :minevnlib-plugin:printVersion | awk 'NR==3')" >> $GITHUB_OUTPUT
        id: plugin
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: "MineVNLib"
          path: ./target/*.jar
      - name: Release
        if: github.ref_name == 'master'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.plugin.outputs.version }}-${{ steps.plugin.outputs.hash }}
          prerelease: true
          name: "MineVNLib - ${{ steps.plugin.outputs.version }}-${{ steps.plugin.outputs.hash }}"
          artifacts: ./target/*.jar
